### ISSUE TITLE
Adapt a design that offers a clean and fast introduction to Circuit Python. 

### ISSUE THREAD

**Issue by Zenith222** [circuitpython/web-editor#1]
I believe proper separation, clearly labeled functions with icons, and prioritized controls make a user interface easier and more fun to use. 

![Circuit Python Online Concept](https://user-images.githubusercontent.com/26575338/125121314-bc749900-e0c1-11eb-8e02-8b772cf80822.png)

Here is a concept that I created to showcase these design principals.

**Comment by makermelissa** [comment]
Closing because I think we have now achieved this with a very similar design.
