### ISSUE TITLE
Web Workflow Serial screen on Full Editor page crashing on non-focus input

### ISSUE THREAD

**Issue by RetiredWizard** [circuitpython/web-editor#172]
### CircuitPython Version

```python
Adafruit CircuitPython 9.0.0-beta.0 on 2024-01-27; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3
9.0.2
9.1.0 beta 0
```

### Workflow(s)

WEB

### Browser(s)

```python
Google Chrome Version 123.0.6312.86 (Official Build) (64-bit)
Chromium Version 123.0.6312.86 (Official Build) snap (64-bit)
```

### Console Log

```python
Load different workflow
index.js:37 Initializing File Transfer Client...
index.js:37 Waiting for connection status to change...
index.js:35 Connected!
```

### Steps

1. Add the following code.py to the board:
```py
a = ''
while a != 'q':
    a = input('_$ ')
```

2. Click on the Restart button
3. Without moving the mouse from the Restart button, press the enter key or the space bar

### Description

In the Serial screen on the Web Workflow Full Editor site, if you use the Reset button to perform a soft reboot and then don't click within the serial screen, the serial screen won't have input focus but it still attempts to respond to keystrokes so if you press the space bar/enter key, code.py (or the REPL if no code.py exists) will attempt to read the input but since the window doesn't have focus there's actually no input there and CircuitPython errors out with an EOFError

```
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
_$ Traceback (most recent call last):
  File "code.py", line 3, in <module>
EOFError: 

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```

### Additional information

Once you know what's going on this isn't really a problem but when it first happened to me, the code.py file I was running didn't handle the error well and the terminal behavior was very confusing.

**Comment by makermelissa** [comment]
Here's the error I get when performing the above procedure:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'zIndex')
    at ButtonValueDialog._removeTopModalLayer (dialogs.js:136:89)
    at ButtonValueDialog._closeModal (dialogs.js:171:18)
    at ButtonValueDialog.close (dialogs.js:191:14)
```
