### ISSUE TITLE
about:blank#blocked error from web bluetooth permission link

### ISSUE THREAD

**Issue by sctv** [circuitpython/web-editor#18]
I get an about:blank#blocked page from CLICKING the "about://flags/#enable-web-bluetooth-new-permissions-backend" link in the code.circuitpython.org page

#17  is a pr that changes the link to chrome://flags/#enable-web-bluetooth-new-permissions-backend 

[CLICKING added for clarity}

**Comment by sctv** [comment]
Now closed
Discussion in the pr.
As I understand it @makermelissa tested the change, and it didn't make an effect. 
Cut and paste of the "about://flags/#enable-web-bluetooth-new-permissions-backend" link is the workaround.

**Comment by sctv** [comment]
Closing

**Comment by makermelissa** [comment]
I wonder if this could be fixed with a bit of JavaScript that sets the window.location when clicked? 🤔
