### ISSUE TITLE
Cant open/edit html files 

### ISSUE THREAD

**Issue by aguaviva** [circuitpython/web-editor#202]
### CircuitPython Version

```python
Adafruit CircuitPython 9.1.0-beta.3 on 2024-05-22; Ai Thinker ESP32-CAM with ESP32
Board ID:ai-thinker-esp32-cam
```

### Workflow(s)

WEB

### Browser(s)

```python
Not dependent on the browser
```

### Steps

create a file as html, then try to open it to edit it.

### Description

![image](https://github.com/circuitpython/web-editor/assets/5200915/dc0ca360-160a-468c-93b9-dfe8fd7096e2)

**Comment by makermelissa** [comment]
I think it's just a matter of adding to a list of text files.

**Comment by aguaviva** [comment]
Is this something you want to take on?

**Comment by makermelissa** [comment]
Yeah, it should be pretty easy. However, syntax highlighting will be a tougher beast to tackle in the future as it is currently python only.
