### ISSUE TITLE
USB Workflow: Disconnecting in cause the page to freeze. 

### ISSUE THREAD

**Issue by urfdvw** [circuitpython/web-editor#21]
Test condition:
- Windows 10 with Chrome 106.0.5249.119 
- Seeed Xiao RP2040
- CircuitPython 7.3.3

Procedure:
- Connect the microcontroller with USB workflow
    - without opening any file
    - from browser console, seeing the serial output
        - which confirms that the code is running
- Click on the `Disconnect` button on the top-right corner
- Result: the browser tab freezes.

Tried:
- checked browser console, seeing log that the same info is repeated fast.
    - probably there is a dead loop caused by disconnection.

![image](https://user-images.githubusercontent.com/17154432/196754963-ac0a4e31-3de0-4f7b-bf84-724e09b98f4b.png)

**Comment by makermelissa** [comment]
Yeah, USB workflow is the newest workflow I added and it definitely needs some work. Thanks for creating the issue.

**Comment by urfdvw** [comment]
Personally, I feel like Disconnecting Serial is not a first class function.
I don't think that is necessary for USB workflow,
as most of the time, closing the browser tab will disconnect,
and there is not a good reason for me to disconnect in the middle of working on a project.

Correct me if I miss anything.

**Comment by makermelissa** [comment]
If you only have a single device, that's fine. However, is if you would like to connect serial to a different usb device or switch workflows then disconnecting is needed.

**Comment by urfdvw** [comment]
> If you only have a single device, that's fine. However, is if you would like to connect serial to a different usb device or switch workflows then disconnecting is needed.

OK I get the switch workflow part. That is interesting.

**Comment by makermelissa** [comment]
As I've been working on redoing USB workflow, I think I've found the cause of the issue. There's a break, but it's only breaking out of a single loop. So what happens is the read loop stops and then it goes into some kind of panic where it continually starts and stops the read loop causing it to freeze.
