### ISSUE TITLE
Update buttons with Hover Effect

### ISSUE THREAD

**Issue by makermelissa** [circuitpython/web-editor#31]
Add a hover effect on buttons by darkening 15%. This should be instant and match adafruit.com.

**Comment by Franqsanz** [comment]
Hello, @makermelissa, I would like to work on this!

**Comment by makermelissa** [comment]
Cool, thanks. It should be a pretty easy one.

**Comment by Franqsanz** [comment]
Great, if I think it's going to be easy.
Question should all buttons have the effect applied?

**Comment by makermelissa** [comment]
Fixed via #33.

**Comment by makermelissa** [comment]
Sorry I forgot to answer you question. Yes, it should be all buttons. If there are any that were missed by #33, we should get those too.
