### ISSUE TITLE
Use web workflow port to connect to the board

### ISSUE THREAD

**Issue by Neradoc** [circuitpython/web-editor#37]
The web workflow doesn't take into account the board's port, and always tries to connect to 80.
When the board is configured uses a different port, it can't connect back to it. (`CIRCUITPY_WEB_API_PORT`)

> Unable to connect. The device 192.168.1.92 was not found. Be sure it is plugged in and set up properly.

(from https://github.com/adafruit/circuitpython/issues/7168 )

**Comment by makermelissa** [comment]
I was wondering about that, hence #29.

**Comment by Neradoc** [comment]
I swear I looked at the issues and missed it somehow 🤦 

I'm not setup to test locally, would changing from `location.hostname` to `location.host` here do it ?

https://github.com/circuitpython/web-editor/blob/7537516c728f6aca2ac4196768f26450ab5fbfd5/assets/js/workflows/web.js#L105-L109

**Comment by makermelissa** [comment]
I was thinking of just setting up a couple of devices and changing the port to something besides 80 and seeing what happens.

**Comment by makermelissa** [comment]
The error message that the person is running into is thrown here: https://github.com/circuitpython/web-editor/blob/main/assets/js/workflows/web.js#L146. There are likely several places that need fixing for alternate ports to work.

**Comment by makermelissa** [comment]
> I'm not setup to test locally, would changing from `location.hostname` to `location.host` here do it ?

Yep, that's basically the fix. For some reason I was thinking there was extra stuff in host (like the protocol), but after looking it up just now, that would have been better than my solution.
