### ISSUE TITLE
Redirect automatically from HTTP to HTTPS

### ISSUE THREAD

**Issue by spovlot** [circuitpython/web-editor#45]
If you just type code.circuitpython.org into the browser, then the USB connection will not work.  You must be on a secure site (https://code.circuitpython.org/) for the JavaScript to work correctly. 

The website should automatically redirect to HTTPS if it goes to the HTTP site.

**Comment by spovlot** [comment]
This can be done via a Pages setting in the repository.  See https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https .

**Comment by makermelissa** [comment]
Good call. I think @tannewt turned that off when we weren't sure how the web workflow and CORS stuff was going to work out. However, now that it's all sorted out, it should be fine to turn back on.

**Comment by tannewt** [comment]
Checked the box!
