### ISSUE TITLE
Add newline after entries in list of discovered devices.

### ISSUE THREAD

**Issue by dgriswo** [circuitpython/web-editor#50]
For ease of reading, it would be useful if a newline was added between device entries.
 
Screenshot of multiple boards attached.

![image](https://user-images.githubusercontent.com/15717486/215515241-468584ba-ebf8-4b73-a148-6aaeb3adcdf7.png)

**Comment by makermelissa** [comment]
Thanks for the suggestion. Yeah, I agree it could use a bit more padding (from left and between items) to separate the items, which should make it easier to read. I'll just use css rather than using an entire new line though as this is meant to also work with mobile devices and space is limited.

**Comment by makermelissa** [comment]
Ok, after playing around with this, now I get what you mean. Yeah, it should be 1 device per line. I think the display css property just needs to be updated or something simple like that.

**Comment by makermelissa** [comment]
Fixed via #55
