### ISSUE TITLE
Index.html help screen popup refers to .env file

### ISSUE THREAD

**Issue by ckostovny** [circuitpython/web-editor#51]
Should this line: 
https://github.com/circuitpython/web-editor/blob/be7c6bb42406519d6b10e0ec7ae3f6936e29a4c5/index.html#L249

refer to settings.toml instead of .env?

**Comment by makermelissa** [comment]
Yes, good catch. This was changed from .env in CP 8.0.0-beta.6.

**Comment by makermelissa** [comment]
I threw in a last second change to fix this in my PR. Fixed via #49.
