### ISSUE TITLE
`TypeError: self._verifyPermission is not a function` when connecting over USB

### ISSUE THREAD

**Issue by huntercaron** [circuitpython/web-editor#60]
I did not see a bug template or anything sorry, so I will try to give all the info I have here.

## Bug

When trying to use the web editor I am running into the following error:

<img width="503" alt="Screenshot 2023-02-11 at 12 02 27" src="https://user-images.githubusercontent.com/4625978/218254636-9eff8e51-8ef9-444d-9278-40b450f2e532.png">

I don't see `self` being referenced anywhere else in the codebase, should it be a `this`?

## Reproduction
1. Connect via USB to Pico W
2. Click "open" or "save" actions
3. Should infinite spinner and error in console

## Info 
```
Adafruit CircuitPython 8.0.0 on 2023-02-06; Raspberry Pi Pico W with rp2040
Board ID:raspberry_pi_pico_w
UID:E66141040356482F
MAC:28:CD:C1:04:37:4B
```

**Comment by makermelissa** [comment]
Yes, good catch. It's probably due to too much switching back and forth between python and javascript. :) Especially since I was working on a python/javascript interface at the time.

**Comment by makermelissa** [comment]
Also, good idea on adding issue templates.
