### ISSUE TITLE
Warn users about experimental chrome flags 

### ISSUE THREAD

**Issue by beaufortfrancois** [circuitpython/web-editor#8]
https://learn.adafruit.com/wirelessly-code-your-bluetooth-device-with-circuitpython/device-setup and https://code.circuitpython.org/ recommends users to enable two experimental flags in Chrome.

The `enable-experimental-web-platform-features` is a flag that affects all websites in Chrome. It should not be enabled unless user knows their browsing experience in Chrome will be impacted.

The `enable-web-bluetooth-new-permissions-backend` flag on the other hand only affects Bluetooth pickers in Chrome. That said, this may break other websites that use Web Bluetooth as well.

Are those flags **really** required?
If not, please remove them from those pages.

**Comment by beaufortfrancois** [comment]
If `enable-experimental-web-platform-features` is to enable the Web Bluetooth API on Linux, you may want to detect this in JavaScript so that non-Linux users don't see these potentially harmful instructions.

```js
if (
  !navigator.bluetooth &&
  navigator.userAgentData.platform == "Linux" &&
  navigator.userAgentData.brands.some((item) => {
    ["Chromium", "Google Chrome"].includes(item.brand);
  })
) {
  // Ask user to enable the experimental web platform features flag and
  // warn them it's going to impact their browsing experience on all websites.
}
```

Regarding the `enable-web-bluetooth-new-permissions-backend`, is it because you use the new `navigator.bluetooth.getDevices()` that has not shipped yet? See https://www.chromestatus.com/feature/4797798639730688

**Comment by beaufortfrancois** [comment]
@tannewt @makermelissa

**Comment by makermelissa** [comment]
I'm planning on testing this out later today. It's very possible that `enable-experimental-web-platform-features` may only be required on certain OS's or even not at all and I'll adjust things accordingly.

> Regarding the `enable-web-bluetooth-new-permissions-backend`, is it because you use the new `navigator.bluetooth.getDevices()` that has not shipped yet? See https://www.chromestatus.com/feature/4797798639730688

That sounds right. I believe the `enable-web-bluetooth-new-permissions-backend` was for re-establishing the bond.

**Comment by makermelissa** [comment]
So far `enable-experimental-web-platform-features` is required on linux to work.

**Comment by makermelissa** [comment]
Ok, both flags are in fact still required for subsequent connections. While MacOS, Windows, and Android can connect initially without the either flag enabled, they are still required to call `navigator.bluetooth.getDevices()` which makes reconnecting SO much easier and a better experience for the user. Linux requires `enable-experimental-web-platform-features` to even make the initial connection.

**Comment by makermelissa** [comment]
So, I'll change the verbiage a bit to let users know what functionality they would be losing, but I still think we should recommend enabling the flags for users because the experience is much better.

**Comment by makermelissa** [comment]
I added a paragraph to the guide outlining what I figured out.

**Comment by beaufortfrancois** [comment]
I have a PR to update the website as well at https://github.com/circuitpython/web-editor/pull/9
Note that Web Bluetooth works on Microsoft Edge browser as well.
