### ISSUE TITLE
Cursor and selection/highlight position dont match

### ISSUE THREAD

**Issue by tyeth** [circuitpython/web-editor#97]
### CircuitPython Version

```python
8.1.0 - beta 2
```
### Workflow(s)

WEB

### Browser(s)

```python
Chrome not-latest 112.0.5615.138 (Official Build) (win11 64-bit)
(it's now updating)
```

### Steps

Goto your board over wifi having ejected/unmounted the usb drive if connected to a device instead of power supply.
Move cursor to end of line in a file like settings.toml.
Use copy and paste keyboard shortcuts with nothing selected.
Cursor moves to new duplicated line.
Use keyboard modifier and arrow keys to select a part of the new line.

Observe **the line above** get highlighted instead

### Description

You can see in the screenshot that the second line (line5) has the cursor, and I've used the keyboard to select my AIO key, but the line above has been highlighted instead.

### Additional information

![Screenshot 2023-05-09 132120](https://github.com/circuitpython/web-editor/assets/6692083/de84fad4-6432-4ffd-9a79-59a01b498a8e)

**Comment by wuhao19920619** [comment]
I have encounter the same problem.
I have recorded a viedo for this issue.
[https://youtu.be/0FzZa3zEMCQ](url)
`Adafruit CircuitPython 8.1.0-beta.2-31-g827eaeb1f on 2023-05-12; VCC-GND YD-ESP32-S3 (N16R8) with ESP32S3
Board ID:yd_esp32_s3_n16r8
UID:4F21AF1E1F4B`
